### ISSUE TITLE
Release 0.1.0 "A New Hope"

### ISSUE THREAD

**Issue by indeyets** [FreeFeed/issues#1]
- [x] Придумать название релизу
  - "A New Hope" тогда уж
    - mbravo [9:53 PM]  не возражаю
    - smallq [9:54 PM]  не возражаю
    - slider23 [9:58 PM]  норм !
    - vocal minority decided.
- [x] Починить websockets
  - [x] Перенести HTTPS-приземление на инстанс — @id
- [x] redirect: http → https — @id
- [x] Включить HSTS — @id
- [x] Включить SPDY — @id
- [x] Запретить доступ к `/v1/users` всем кроме `136.243.23.88` — @id
- [x] Новая «тема» оформления — @slider23
  - [x] Убрать слово Pepyatka отовсюду кроме короткого упоминания имени движка - @slider23 + @berkus
  - [x] Убрать ссылку на «регистрацию» - @slider23 
  - [x] Поставить ссылку на `about.freefeed.net` - @slider23 
  - [x] Поставить ссылку на google-форму вопросов - @slider23 
  - [x] Поставить favicon (а также apple/win8-metro иконки) - @slider23 
  - [x] [nice-to-have] Google Analytics - @payalnik
- [x] На «серверной» части включить флажок «не регистрировать по паролям» - @id 
  - acceptHashedPasswordsOnly
- [x] обнулить базу перед запуском
- [x] перенастроить деплой на https://github.com/FreeFeed/pepyatka-html (ветка `whitelabel`) - @id
- группы пока исключаем, когда будет готово - выкатим хотфикс

Секция "хотчикс^Wхотфикс":
- [ ] запускать по ноде на ядро и балансить nginx-ом - @id
- [x] [optional] Довести набор шифров по [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=test.freefeed.net) до `A` (сейчас `A-`) – @id 
- [ ] починить «группы» pepyatka/pepyatka-server#190, pepyatka/pepyatka-html#214 — @yole
- [ ] Новая «тема» оформления "Fresh" — @slider23

**Comment by slider23** [comment]
Как должна выглядеть ссылка на about.freefeed.net ? В футере или под шапкой на заметной панели ?
Где взят ссылку на google-форму и где её положить ?

**Comment by indeyets** [comment]
@slider23 ссылка думаю в футере, а гугл-форма тут: https://docs.google.com/forms/d/1N6zo9BGu8Hv6aORTfbdjWoFt6xyikTfv-CJA4JoTzmo/viewform?usp=send_form

**Comment by berkus** [comment]
https://hackpad.com/0.1.0-Known-issues-hdvOoyeQ2zu

**Comment by hsw** [comment]
Можно gzip для JS/CSS включить?  config.js 1.1Mb долго грузится.

**Comment by indeyets** [comment]
@hsw отдельным багом, пожалуйста :)
спасибо

**Comment by vdrandom** [comment]
Импортировал аккаунт перед тем, как френдфид распилили, залогинился - аккаунт пустой. Ни записей, ни друзяк. @vdrandom

**Comment by xekc** [comment]
@vdrandom так и должно быть. пока экаунты всех пользователей восстанавливаются без контента. восстановление будет сделано отдельным шагом.

**Comment by vdrandom** [comment]
А, понятно. В любом случае спасибо за freefeed! :)
