### ISSUE TITLE
Migration to S3

### ISSUE THREAD

**Issue by clbn** [FreeFeed/issues#13]
So, we sorta almost have S3 support (pepyatka/pepyatka-server#272) and are really eager to migrate all those cats and naked girls to AWS, right? Besides enabling S3 in config, we have to do following things:
- [x] Update `pepyatka-ansible` with the new config structure.
- [x] Prepare domain `https://media.freefeed.net` served by nginx for using as a vanity URL and frontend before the S3. Don't forget to put there proper SSL certificate.
- [x] Add simple proxying rule to `nginx.conf` behind `media.freefeed.net`: just proxy every GET/HEAD request to `https://freefeed-media.s3.amazonaws.com`.
- [x] Create S3 bucket `freefeed-media.s3.amazonaws.com`, check all the permissions and stuff...
- [x] Add CORS to that bucket to make @davidmz dance in excitement. (@davidmz: "CORS headers may be added at nginx level.")
- [x] Copy files to the production S3 bucket. Please pay attention to paths' changes:

```
/attachments/original/xxx.jpg -> /attachments/xxx.jpg ("original" is removed)
/attachments/thumbnails/xxx.jpg -> /attachments/thumbnails/xxx.jpg (no change)
```

**NB.** Do not move profile pics, there is no S3 support for them for the time being.
- [x] Add redirect for two paths (see above) to `nginx.conf` behind `freefeed.net`. This way old attachments' URLs are not gonna rot.
- [x] FINALLY we can _pull the switch_ in the config. Don't forget to update `config.media.url` and `config.media.storage.*` with prod values.
- [x] _Anything else?_

**Comment by davidmz** [comment]
CORS headers may be added at nginx level.

**Comment by clbn** [comment]
@davidmz Fair enough, added your comment to the list. Thanks!

**Comment by berkus** [comment]
- [x] create domain for micropeppa media
- [x] copy micropeppa files to test bucket - prepare a work script to do this with one command along the way
- [x] set up micropeppa nginx to redirect correctly
- [x] deploy S3-enabled config to micropeppa

**Comment by berkus** [comment]
- [x] Test old links - should work with S3! 
  Like:
  https://micropeppa.freefeed.net/attachments/thumbnails/c4480afa-63a3-4033-983d-bd511d63e2a3.jpg
  https://micropeppa.freefeed.net/attachments/original/c4480afa-63a3-4033-983d-bd511d63e2a3.jpg

https://micropeppa.freefeed.net/attachments/original/2d9e5ef0-49f7-42cf-9179-b443fc66c786.mp3

https://micropeppa.freefeed.net/attachments/thumbnails/c842f6fc-cd4d-4880-af66-ef48bd9f1121.jpg
https://micropeppa.freefeed.net/attachments/original/c842f6fc-cd4d-4880-af66-ef48bd9f1121.jpg

**Comment by berkus** [comment]
For copying on production use the following schema:
- [x] Start copying to S3
- [x] After first round of copying done, pull the plug and start uploading/serving files from S3
- [x] Run copy to S3 again, probably without copying already existing files (`aws s3 sync`)

`aws s3 sync --acl public-read . s3://bucket/path/`

**Comment by berkus** [comment]
Only 1 extra picture was added by users during s3 deploy! All in sync now.
