### ISSUE TITLE
[Verified] Posts created more than 18 days ago (before May 23rd) have /# instead of direct link

### ISSUE THREAD

**Issue by smallq-git** [FreeFeed/issues#7]
This exists on live: all posts created before May 23rd don't have direct links.

Post created on May 22nd:
![image](https://cloud.githubusercontent.com/assets/7983303/8070582/037ca71e-0f0b-11e5-8be7-a7b9283f9043.png)

Post created on May 23rd:
![image](https://cloud.githubusercontent.com/assets/7983303/8070596/1d1ff45a-0f0b-11e5-9280-ebf0425a5e10.png)

**Comment by smallq-git** [comment]
On peppa this change happens on May 21st (or rather between 4 am Msk 21st and 2 am Msk 22nd).

**Comment by smallq-git** [comment]
Note that this is not reproduced on nano/vanilla

**Comment by epicmonkey** [comment]
The root cause is a new attribute we've added to support groups: `postedTo`, i.e. we build link using this code `{#link-to 'post' post.content.postedTo.firstObject.user.username post.content.id\
 (query-params offset=0) class="datetime"}}` and old posts do not have postedTo attribute. we need a fallback.

**Comment by epicmonkey** [comment]
This one is resolved in https://github.com/pepyatka/pepyatka-html/commit/c845597037a4569a8bef205e14ea4ea219994d36

**Comment by smallq-git** [comment]
Sadly, no.

**Comment by epicmonkey** [comment]
Oookay, I could be wrong and that fix wasn't promited to peppa time I wrote my comment.

**Comment by smallq-git** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/7983303/8240952/0401074c-160f-11e5-9211-0569e60266ce.png)
